language: java

before_script:
 - echo "MAVEN_OPTS='-Xmx3g'" > ~/.mavenrc

script: 
  - cd pnmlFw-Releng ; mvn generate-sources install -Pall ; cd -
  - ls -lah PnmlFramework_UpdateSite

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: PnmlFramework_UpdateSite/target/repository
#  upload_dir: night-updates/
  on:
    branch: master

cache:
  directories:
    - '$HOME/.m2/repository'
